package com.aiagent.network

import com.aiagent.data.model.GeneratedFile
import com.google.gson.annotations.SerializedName
import okhttp3.ResponseBody
import retrofit2.Response
import retrofit2.http.*

data class ProjectRequest(
    val agentType: String,
    val projectName: String,
    val description: String,
    val features: List<String>,
    val language: String = "kotlin",
    val includeBackend: Boolean = false,
    val provider: String,
    val model: String?,
    val api_key: String,
    val base_url: String?
)

data class ProjectResponse(
    val success: Boolean,
    val message: String,
    val files: List<GeneratedFile>,
    val projectStructure: String,
    val tokens_used: Int?,
    val generated_at: String
)

data class ChatMessageRequest(
    val role: String,
    val content: String
)

data class ChatRequest(
    val messages: List<ChatMessageRequest>,
    val provider: String,
    val api_key: String,
    val model: String?,
    val base_url: String?,
    val stream: Boolean = false
)

data class ChatResponse(
    val response: String,
    val timestamp: String
)

data class GitHubPushRequest(
    val token: String,
    val repo_name: String,
    val files: List<GeneratedFile>,
    val branch: String = "main",
    val commit_message: String = "Generated by AI Agent Pro"
)

data class GitHubPushResponse(
    val success: Boolean,
    val message: String,
    val repo_url: String
)

data class ProviderInfo(
    val id: String,
    val name: String,
    val default_model: String,
    val base_url: String
)

data class ProvidersResponse(
    val providers: List<ProviderInfo>
)

data class HealthResponse(
    val status: String,
    val version: String,
    val supported_providers: List<String>,
    val timestamp: String
)

interface ApiService {
    
    @POST("generate/project")
    suspend fun generateProject(
        @Body request: ProjectRequest
    ): Response<ProjectResponse>
    
    @POST("chat")
    suspend fun sendChatMessage(
        @Body request: ChatRequest
    ): Response<ChatResponse>
    
    @POST("github/push")
    suspend fun pushToGitHub(
        @Body request: GitHubPushRequest
    ): Response<GitHubPushResponse>
    
    @POST("download/zip")
    @Streaming
    suspend fun downloadZip(
        @Query("project_name") projectName: String,
        @Body files: List<GeneratedFile>
    ): Response<ResponseBody>
    
    @GET("providers")
    suspend fun getProviders(): Response<ProvidersResponse>
    
    @GET("health")
    suspend fun healthCheck(): Response<HealthResponse>
}
