package com.aiagent.repository

import com.aiagent.data.db.ProjectDao
import com.aiagent.data.model.GeneratedFile
import com.aiagent.data.model.GeneratedProject
import com.aiagent.network.*
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ProjectRepository @Inject constructor(
    private val apiService: ApiService,
    private val projectDao: ProjectDao
) {
    // Local Database Operations
    fun getAllProjects(): Flow<List<GeneratedProject>> = projectDao.getAllProjects()
    
    fun getFavoriteProjects(): Flow<List<GeneratedProject>> = projectDao.getFavoriteProjects()
    
    fun getProjectsByAgentType(agentType: String): Flow<List<GeneratedProject>> = 
        projectDao.getProjectsByAgentType(agentType)
    
    fun searchProjects(query: String): Flow<List<GeneratedProject>> = 
        projectDao.searchProjects(query)
    
    suspend fun getProjectById(projectId: String): GeneratedProject? = 
        projectDao.getProjectById(projectId)
    
    suspend fun saveProject(project: GeneratedProject) = 
        projectDao.insertProject(project)
    
    suspend fun updateProject(project: GeneratedProject) = 
        projectDao.updateProject(project)
    
    suspend fun deleteProject(project: GeneratedProject) = 
        projectDao.deleteProject(project)
    
    suspend fun toggleFavorite(projectId: String, isFavorite: Boolean) = 
        projectDao.updateFavoriteStatus(projectId, isFavorite)
    
    // Remote API Operations
    fun generateProject(
        agentType: String,
        projectName: String,
        description: String,
        features: List<String>,
        provider: String,
        model: String?,
        apiKey: String,
        baseUrl: String?
    ) = flow {
        emit(ApiResult.Loading)
        try {
            val request = ProjectRequest(
                agentType = agentType,
                projectName = projectName,
                description = description,
                features = features,
                provider = provider,
                model = model,
                api_key = apiKey,
                base_url = baseUrl
            )
            
            val response = apiService.generateProject(request)
            if (response.isSuccessful && response.body() != null) {
                emit(ApiResult.Success(response.body()!!))
            } else {
                emit(ApiResult.Error("Error: ${response.code()} - ${response.message()}"))
            }
        } catch (e: Exception) {
            emit(ApiResult.Error(e.message ?: "Unknown error"))
        }
    }
    
    fun pushToGitHub(
        token: String,
        repoName: String,
        files: List<GeneratedFile>,
        branch: String = "main",
        commitMessage: String = "Generated by AI Agent Pro"
    ) = flow {
        emit(ApiResult.Loading)
        try {
            val request = GitHubPushRequest(
                token = token,
                repo_name = repoName,
                files = files,
                branch = branch,
                commit_message = commitMessage
            )
            
            val response = apiService.pushToGitHub(request)
            if (response.isSuccessful && response.body() != null) {
                emit(ApiResult.Success(response.body()!!))
            } else {
                emit(ApiResult.Error("GitHub push failed: ${response.message()}"))
            }
        } catch (e: Exception) {
            emit(ApiResult.Error(e.message ?: "Unknown error"))
        }
    }
    
    suspend fun downloadProjectZip(projectName: String, files: List<GeneratedFile>) = 
        apiService.downloadZip(projectName, files)
}
